import { ISymptomsDiseases } from '../../interfaces/ISymptomsDiseases.js'
import SymptomsDiseasesModel from '../../models/SymptomsDiseasesModel.js'

const createSymptomsDiseases = {
  name: 'create-symptoms-diseases',
  description: 'Cria doenças com seus sintomas (IA simulada)',
  async run() {
    console.log('🚀 Criando condições médicas...')

    const diseases: ISymptomsDiseases[] = [
      {
        disease: 'Influenza',
        symptoms: {
          fever: 1,
          chills: 1,
          musclePain: 1,
          fatigue: 1,
          headache: 1,
          dryCough: 1,
          soreThroat: 1,
          runnyNose: 1,
          sneezing: 1,
          shortnessOfBreath: 0,
          nauseaVomiting: 0,
          diarrhea: 0,
          abdominalPain: 0,
          skinRash: 0,
          chestPain: 0,
          mentalConfusion: 0,
          neckStiffness: 0,
          jaundice: 0,
          bleeding: 0,
          jointSwelling: 0,
          lossOfTasteSmell: 0,
          dizziness: 0,
          coughWithPhlegm: 0,
          wheezing: 0,
          burningUrination: 0
        }
      },
      {
        disease: 'COVID-19',
        symptoms: {
          fever: 1,
          chills: 1,
          musclePain: 1,
          fatigue: 1,
          headache: 1,
          dryCough: 1,
          soreThroat: 1,
          runnyNose: 1,
          sneezing: 0,
          shortnessOfBreath: 1,
          nauseaVomiting: 1,
          diarrhea: 1,
          abdominalPain: 0,
          skinRash: 0,
          chestPain: 1,
          mentalConfusion: 1,
          neckStiffness: 0,
          jaundice: 0,
          bleeding: 0,
          jointSwelling: 0,
          lossOfTasteSmell: 1,
          dizziness: 1,
          coughWithPhlegm: 0,
          wheezing: 0,
          burningUrination: 0
        }
      },
      {
        disease: 'Pneumonia',
        symptoms: {
          fever: 1,
          chills: 1,
          musclePain: 1,
          fatigue: 1,
          headache: 0,
          dryCough: 0,
          soreThroat: 0,
          runnyNose: 0,
          sneezing: 0,
          shortnessOfBreath: 1,
          nauseaVomiting: 0,
          diarrhea: 0,
          abdominalPain: 0,
          skinRash: 0,
          chestPain: 1,
          mentalConfusion: 1,
          neckStiffness: 0,
          jaundice: 0,
          bleeding: 0,
          jointSwelling: 0,
          lossOfTasteSmell: 0,
          dizziness: 1,
          coughWithPhlegm: 1,
          wheezing: 1,
          burningUrination: 0
        }
      },
      {
        disease: 'Asthma',
        symptoms: {
          fever: 0,
          chills: 0,
          musclePain: 0,
          fatigue: 1,
          headache: 0,
          dryCough: 1,
          soreThroat: 0,
          runnyNose: 0,
          sneezing: 1,
          shortnessOfBreath: 1,
          nauseaVomiting: 0,
          diarrhea: 0,
          abdominalPain: 0,
          skinRash: 0,
          chestPain: 1,
          mentalConfusion: 0,
          neckStiffness: 0,
          jaundice: 0,
          bleeding: 0,
          jointSwelling: 0,
          lossOfTasteSmell: 0,
          dizziness: 0,
          coughWithPhlegm: 0,
          wheezing: 1,
          burningUrination: 0
        }
      },
      {
        disease: 'Diabetes',
        symptoms: {
          fever: 0,
          chills: 0,
          musclePain: 0,
          fatigue: 1,
          headache: 1,
          dryCough: 0,
          soreThroat: 0,
          runnyNose: 0,
          sneezing: 0,
          shortnessOfBreath: 1,
          nauseaVomiting: 1,
          diarrhea: 0,
          abdominalPain: 1,
          skinRash: 0,
          chestPain: 0,
          mentalConfusion: 1,
          neckStiffness: 0,
          jaundice: 0,
          bleeding: 0,
          jointSwelling: 0,
          lossOfTasteSmell: 0,
          dizziness: 1,
          coughWithPhlegm: 0,
          wheezing: 0,
          burningUrination: 0,
          frequentUrination: 1,
          thirst: 1,
          blurredVision: 1
        }
      },
      {
        disease: 'Dengue',
        symptoms: {
          fever: 1,
          chills: 1,
          musclePain: 1,
          fatigue: 1,
          headache: 1,
          dryCough: 0,
          soreThroat: 0,
          runnyNose: 0,
          sneezing: 0,
          shortnessOfBreath: 0,
          nauseaVomiting: 1,
          diarrhea: 0,
          abdominalPain: 1,
          skinRash: 1,
          chestPain: 0,
          mentalConfusion: 0,
          neckStiffness: 0,
          jaundice: 0,
          bleeding: 1,
          jointSwelling: 1,
          lossOfTasteSmell: 0,
          dizziness: 1,
          coughWithPhlegm: 0,
          wheezing: 0,
          burningUrination: 0
        }
      },
      {
        disease: 'Kidney Infection',
        symptoms: {
          fever: 1,
          chills: 1,
          musclePain: 0,
          fatigue: 1,
          headache: 0,
          dryCough: 0,
          soreThroat: 0,
          runnyNose: 0,
          sneezing: 0,
          shortnessOfBreath: 0,
          nauseaVomiting: 1,
          diarrhea: 0,
          abdominalPain: 1,
          skinRash: 0,
          chestPain: 0,
          mentalConfusion: 0,
          neckStiffness: 0,
          jaundice: 0,
          bleeding: 0,
          jointSwelling: 0,
          lossOfTasteSmell: 0,
          dizziness: 1,
          coughWithPhlegm: 0,
          wheezing: 0,
          burningUrination: 1,
          backPain: 1
        }
      },
      {
        disease: 'Anemia',
        symptoms: {
          fever: 0,
          chills: 0,
          musclePain: 0,
          fatigue: 1,
          headache: 1,
          dryCough: 0,
          soreThroat: 0,
          runnyNose: 0,
          sneezing: 0,
          shortnessOfBreath: 1,
          nauseaVomiting: 0,
          diarrhea: 0,
          abdominalPain: 0,
          skinRash: 0,
          chestPain: 0,
          mentalConfusion: 0,
          neckStiffness: 0,
          jaundice: 0,
          bleeding: 0,
          jointSwelling: 0,
          lossOfTasteSmell: 0,
          dizziness: 1,
          coughWithPhlegm: 0,
          wheezing: 0,
          burningUrination: 0,
          weightLoss: 1
        }
      }
    ]

    await SymptomsDiseasesModel.deleteMany()
    await SymptomsDiseasesModel.insertMany(diseases)

    console.log(`✅ ${diseases.length} doenças inseridas com sucesso!`)
    process.exit()
  }
}

export default createSymptomsDiseases
